language: java

jdk:
  - openjdk8

sudo: required

branches:
  only:
  - master
  - /^release-.*$/
  - /^test-.*$/

install: mvn compile -Dmaven.javadoc.skip=true | grep -v "Downloading\|Downloaded"

before_script:
  - $TRAVIS_DIR/install-hugegraph-from-source.sh $TRAVIS_BRANCH | grep -v "Downloading\|Downloaded"

script:
  - mvn test -Dtest=UnitTestSuite
  - mvn test -Dtest=ApiTestSuite
  - mvn test -Dtest=FuncTestSuite

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
  - TRAVIS_DIR=assembly/travis
  - COMMIT_ID=9ef6796dc9c60679ffbe49e60fe31c7d23818f55
