name: hugegraph-client ci

on:
  push:
    branches:
      - master
      - /^release-.*$/
      - /^test-.*$/
  pull_request:
    branches:
      - master
      - /^release-.*$/
      - /^test-.*$/

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      TRAVIS_DIR: assembly/travis
      COMMIT_ID: 2dd2d7c3fd7cb42cd7338d70a73e04b0c5604487
    steps:
      - name: Install JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Compile
        run: |
          mvn compile -Dmaven.javadoc.skip=true | grep -v "Downloading\|Downloaded"

      - name: Prepare env and service
        run: |
          $TRAVIS_DIR/install-hugegraph-from-source.sh $COMMIT_ID | grep -v "Downloading\|Downloaded"

      - name: Run test
        run: |
          mvn test -Dtest=UnitTestSuite
          mvn test -Dtest=ApiTestSuite
          mvn test -Dtest=FuncTestSuite

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: target/jacoco.xml
